name: Deploy Redshift Serverless

on:
  workflow_dispatch:

jobs:
  deploy-redshift:
    runs-on: ubuntu-latest
    env:
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      SECURITY_GROUP_ID: ${{ secrets.SECURITY_GROUP_ID }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      REDSHIFT_CLUSTER_NAME: ${{ secrets.REDSHIFT_CLUSTER_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: pip install boto3 python-dotenv

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActionsSession
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Check if the Redshift Cluster exists
        run: |
          CLUSTER_STATUS=$(aws redshift describe-clusters --cluster-identifier $REDSHIFT_CLUSTER_NAME --query "Clusters[0].ClusterStatus" --output text || echo "NOT_FOUND")
          echo "Cluster Status: $CLUSTER_STATUS"
          if [[ "$CLUSTER_STATUS" == "available" ]]; then
            echo "Redshift is already running. Skipping deployment."
            exit 0
          fi
      
      - name: Set Up S3 IAM Role
        run: python infrastructure/aws_cdk/setup_s3_iam_role.py

      - name: Set Up Redshift
        run: python infrastructure/aws_cdk/setup_redshift.py

      - name: Update Security Group
        run: python infrastructure/aws_cdk/update_security_group.py